/**
 * Horus v2 Type Definitions
 *
 * Flexible TypeScript interfaces for the two-stage agentic pipeline.
 * Stage 1: Analysis Agent → N Sections
 * Stage 2: N Parallel Research Agents → Enriched Sections
 */

import type { Id } from "../../_generated/dataModel";
import type { QualityTier } from "../metrics";

// ─────────────────────────────────────────────────────────────────
// Common Types
// ─────────────────────────────────────────────────────────────────

export type V2AgentName = "analysis" | "research";

export type V2PipelineStatus =
  | "pending"
  | "analyzing"
  | "researching"
  | "complete"
  | "error";

export type EvidenceTier = "S" | "A" | "B" | "C" | "D";

export type EvidenceStrengthLevel = "strong" | "moderate" | "limited";

/** Severity level for clinical findings */
export type SeverityLevel = "critical" | "severe" | "moderate" | "mild" | "profound";

/** Key finding with severity level for display */
export interface KeyFinding {
  text: string;
  severity: SeverityLevel;
}

/** Radar chart scores for visual summary (1-10 scale) */
export interface RadarScores {
  /** ROM quality - peak flexion, extension, average ROM */
  flexibility: number;
  /** ROM CoV - movement repeatability */
  consistency: number;
  /** Asymmetry metrics - ROM, velocity, global */
  symmetry: number;
  /** RMS Jerk - movement quality */
  smoothness: number;
  /** Timing, coordination - temporal lag, phase shift, cross-correlation */
  control: number;
}

// ─────────────────────────────────────────────────────────────────
// Analysis Agent Output (Stage 1)
// ─────────────────────────────────────────────────────────────────

/**
 * Q&A clinical reasoning pair.
 * Each section can have multiple Q&A pairs showing clinical thought process.
 */
export interface QAReasoning {
  question: string;
  answer: string;
}

/**
 * Metric contribution to a finding.
 * Links findings to specific metrics with context.
 */
export interface MetricContribution {
  /** Metric name (e.g., "leftLeg.peakAngularVelocity") */
  metric: string;
  /** Raw value */
  value: number;
  /** Unit (e.g., "°/s", "%", "ms") */
  unit: string;
  /** How this metric contributes to the finding */
  role: string;
  /** Type of metric */
  type?: "raw" | "computed" | "derived" | "comparison";
  /** Additional context */
  context?: string;
  /** Allow custom fields */
  [key: string]: unknown;
}

/**
 * Clinical section generated by the Analysis Agent.
 * Flexible schema allowing custom domains and additional data.
 */
export interface Section {
  /** Unique section ID */
  id: string;
  /** Display title */
  title: string;
  /** Domain - standard or custom */
  domain: string;
  /** Severity level for visual indication */
  severity: SeverityLevel;
  /** Priority for display ordering (1-10, higher = more important) */
  priority: number;
  /** Clinical narrative explaining the finding */
  clinicalNarrative: string;
  /** How each joint contributes to this finding (flexible keys) */
  jointContributions: Record<string, string>;
  /** Q&A reasoning pairs showing clinical thought process */
  qaReasoning: QAReasoning[];
  /** Metrics that support this finding */
  metricContributions: MetricContribution[];
  /** Search queries for research phase */
  searchQueries: string[];
  /** Initial recommendations (before research enrichment) */
  recommendations: string[];
  /** Whether this section needs research enrichment */
  needsResearch: boolean;
  /** Allow custom additional data */
  additionalData?: Record<string, unknown>;
}

/**
 * Analysis Agent output containing all clinical sections.
 */
export interface AnalysisAgentOutput {
  sessionId: string;
  /** Radar chart scores for visual summary */
  radarScores: RadarScores;
  /** Key clinical findings with severity */
  keyFindings: KeyFinding[];
  /** Clinical implications summary */
  clinicalImplications: string;
  /** All generated sections */
  sections: Section[];
  /** Overall clinical summary */
  summary: string;
  /** Key strengths identified */
  strengths: string[];
  /** Key weaknesses identified */
  weaknesses: string[];
  /** Unified recommendations (prioritized) */
  recommendations: string[];
  /** Timestamp of analysis */
  analyzedAt: number;
}

// ─────────────────────────────────────────────────────────────────
// Research Agent Output (Stage 2)
// ─────────────────────────────────────────────────────────────────

/**
 * Citation with evidence quality tier.
 */
export interface Citation {
  /** Cited text excerpt */
  text: string;
  /** Source name/title */
  source: string;
  /** Quality tier (S = systematic review, D = general) */
  tier: EvidenceTier;
  /** Allow custom fields */
  [key: string]: unknown;
}

/**
 * Quality link collected during research.
 */
export interface QualityLink {
  /** Full URL */
  url: string;
  /** Page title */
  title: string;
  /** Quality tier */
  tier: EvidenceTier;
  /** Domain (e.g., "pubmed.ncbi.nlm.nih.gov") */
  domain: string;
  /** How this link is relevant to the section */
  relevance: string;
  /** Allow custom fields */
  [key: string]: unknown;
}

/**
 * User-friendly explanation of the clinical finding.
 * Written in accessible language for patients.
 */
export interface UserExplanation {
  /** Brief summary (1-2 sentences) */
  summary: string;
  /** What the finding means in simple terms */
  whatItMeans: string;
  /** Why this matters for the patient */
  whyItMatters: string;
  /** Optional analogy to make it relatable */
  analogy?: string;
  /** Allow custom explanation fields */
  [key: string]: string | undefined;
}

/**
 * Evidence strength assessment.
 */
export interface EvidenceStrength {
  /** Overall evidence level */
  level: EvidenceStrengthLevel;
  /** Additional notes about evidence quality */
  notes?: string;
}

/**
 * Enriched section after research phase.
 * Extends the original section with evidence and explanations.
 */
export interface EnrichedSection extends Section {
  /** Narrative enriched with citations and evidence */
  enrichedNarrative: string;
  /** User-friendly explanation for patients (uses "the patient" framing) */
  userExplanation: UserExplanation;
  /** Supporting citations with tier ratings */
  citations: Citation[];
  /** Quality links collected during research */
  links: QualityLink[];
  /** Evidence strength assessment */
  evidenceStrength: EvidenceStrength;
  /** Whether evidence contradicted original finding (agent rewrote) */
  wasContradicted: boolean;
  /** Single unified recommendation for this section */
  recommendation: string;
  /** Whether enrichment failed (timeout/error) */
  enrichmentFailed?: boolean;
  /** Error message if enrichment failed */
  enrichmentError?: string;
}

/**
 * Research Agent output for a single section.
 */
export interface ResearchAgentOutput {
  /** Original section ID */
  sectionId: string;
  /** Enriched section data */
  enrichedSection: EnrichedSection;
  /** New cache entries to save (tier B+) */
  newCacheEntries: CacheEntry[];
  /** Token usage for this research agent */
  tokenUsage: TokenUsage;
  /** Duration in milliseconds */
  durationMs: number;
}

// ─────────────────────────────────────────────────────────────────
// Cache Types
// ─────────────────────────────────────────────────────────────────

/**
 * Entry to save to research cache.
 */
export interface CacheEntry {
  /** Search terms that led to this finding */
  searchTerms: string[];
  /** Quality tier */
  tier: EvidenceTier;
  /** Citation text */
  citation: string;
  /** Source URL if available */
  url?: string;
  /** Key findings */
  findings: string[];
  /** Relevance score 0-100 */
  relevanceScore: number;
}

// ─────────────────────────────────────────────────────────────────
// Pipeline Types
// ─────────────────────────────────────────────────────────────────

/**
 * Token usage tracking.
 */
export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  estimatedCost: number;
}

/**
 * Individual agent execution result.
 */
export interface AgentResult<T> {
  success: boolean;
  output?: T;
  error?: string;
  tokenUsage: TokenUsage;
  durationMs: number;
}

/**
 * Full v2 pipeline output.
 */
export interface V2PipelineOutput {
  sessionId: string;
  patientId?: Id<"users">;
  /** Radar chart scores for visual summary */
  radarScores: RadarScores;
  /** Key clinical findings with severity */
  keyFindings: KeyFinding[];
  /** Clinical implications summary */
  clinicalImplications: string;
  /** Original sections from Analysis Agent */
  sections: Section[];
  /** Enriched sections from Research Agents */
  enrichedSections: EnrichedSection[];
  /** Overall summary */
  summary: string;
  /** Top strengths */
  strengths: string[];
  /** Top weaknesses */
  weaknesses: string[];
  /** Unified recommendations (prioritized) */
  recommendations: string[];
  /** Sections that failed enrichment (returned original) */
  failedEnrichments: string[];
  /** Token usage breakdown */
  tokenUsage: {
    analysis: TokenUsage;
    research: TokenUsage[];
    total: TokenUsage;
  };
  /** Total pipeline duration */
  totalDurationMs: number;
  /** Timestamps */
  startedAt: number;
  completedAt: number;
}

/**
 * v2 Pipeline state for database storage.
 */
export interface V2PipelineState {
  sessionId: string;
  status: V2PipelineStatus;
  /** Analysis Agent output (if complete) */
  analysisOutput?: AnalysisAgentOutput;
  /** Final enriched output (if complete) */
  output?: V2PipelineOutput;
  /** Error info if failed */
  error?: {
    agent: V2AgentName;
    message: string;
    sectionId?: string;
  };
  /** Timestamps */
  startedAt: number;
  completedAt?: number;
}

// ─────────────────────────────────────────────────────────────────
// Input Types (reuse from v1)
// ─────────────────────────────────────────────────────────────────

// Re-export SessionMetrics from v1 types
export type { SessionMetrics, PerLegMetricValues, BilateralMetricValues } from "../types";

